general:
  remote_storage: s3

clickhouse:
  host: localhost
  port: 9000
  skip_tables:
    - system.*
    - INFORMATION_SCHEMA.*
    - information_schema.*

s3:
  endpoint: http://minio:9000/ch-backups
  access_key: admin
  secret_key: password123
  region: us-east-1